name: 'Backend Continuous Integration'
on:
  workflow_dispatch:

  pull_request:
    paths:
      - starter/backend/**
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: cd starter/backend && pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.ouputs.python-version }}
      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev
      - name: Run lint
        run: cd starter/backend && pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: cd starter/backend && pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.ouputs.python-version }}
      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev
      - name: Run lint
        run: cd starter/backend && pipenv run pytest

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: cd starter/backend && pip install pipenv
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.ouputs.python-version }}
      - name: Install dependencies
        run: cd starter/backend && pipenv install --dev
      - name: Run lint
        run: cd starter/backend && pipenv run pytest
